%% Biomass Energy Class Definition
% 06-September, 2011
% Adedamola Adepetu, aadepetu@masdar.ac.ae
%%
classdef BiomassEnergy < Behavior
    properties
        conversion_method;          % if value is 1, Combustion/Steam Turbine cycle and if its a 2, its a Gasification/Gas-Steam Combined Cycle (input)
        gas_turbine_capacity;       % capacity of gas turbine for gas-steam combined cycle (MW) (input)
        steam_turbine_capacity;     % capacity of steam turbine (MW) (input)
        plant_capacity;             % biomass plant rated capacity (MW)
        biomass_lhv;                % the lower heating value of the biomass fuel used in (kJ/kg) (input)
        plant_efficiency;           % the annual efficiency of the biomass plant (input)
        full_load_hours;            % the annual full load hours of plant operation (input)
        biomass_flow_rate;          % the amount of fuel required annualy (Tonne/year)
        annual_energy_generated;   % The amount of electricity generated from the power plant annualy (MWh)

    end
    methods
        function obj = BiomassEnergy()
            obj = obj@Behavior('Biomass Power Plant', ...
                'Estimates the energy generated by a biomass power plant, its capacity and the amount if fuel required annualy', ...
                'MWh','[0,inf)');
        end
        
        function PlotCellBiomassEnergy(obj)
            figure
            title(['Biomass Energy (' obj.units ')'])
            obj.PlotCellValueMap(obj.annual_energy_generated)
        end
    end
    methods(Access=protected)
        %% EvaluateImpl Function
        
        function val = EvaluateImpl(obj)      
            
            % Set city identifier
            city = CityNet.instance().city;
            
            % Search for energy system identifier       
            for i = 1:length(city.systems)
                if strcmp(city.systems(i).name,'Energy')==1
                    sys_index = i;
                    break
                end
            end      
            
            % Search for Biomass Station identifier in Energy Layer
            for i = 1:length(city.systems(sys_index).nodes)
                if strcmp(city.systems(sys_index).nodes(i).type.name,'Biomass Station')
                    % Store node ID
                    node_index = i;
                    break
                end
            end          
            
            % Set Biomass Station Identifier
            biomass = city.systems(sys_index).nodes(node_index);
            
            obj.conversion_method = biomass.GetNodeTypeAttributeValue('Conversion Method');
            obj.steam_turbine_capacity = biomass.GetNodeTypeAttributeValue('Steam Turbine Capacity');
            obj.gas_turbine_capacity = biomass.GetNodeTypeAttributeValue('Gas Turbine Capacity');
            obj.biomass_lhv = biomass.GetNodeTypeAttributeValue('Fuel LHV');
            obj.plant_efficiency = biomass.GetNodeTypeAttributeValue('Plant Conversion Efficiency');
            obj.full_load_hours = biomass.GetNodeTypeAttributeValue('Full Load Hours of Operation');
            
            
            if obj.conversion_method == 1
                obj.plant_capacity = obj.steam_turbine_capacity;
            else
                obj.plant_capacity = obj.steam_turbine_capacity + obj.gas_turbine_capacity;
            end
            
            obj.biomass_flow_rate = obj.plant_capacity*3.6*obj.full_load_hours/(obj.biomass_lhv*obj.plant_efficiency);
            obj.annual_energy_generated = obj.full_load_hours*obj.plant_capacity;
            
            
            
            %% Assign null value to val
            val = obj.annual_energy_generated;
            
        end
    end
end
                  