%% TotalResidentialWater Class Definition
% The TotalResidentialWater behavior calculates the total amount of
% residential water demand generated by the city by application type. 
% The application types are as follows:
% - Kitchen
% - Faucets
% - Shower
% - Toilets
% - Laundry
%
% 12-August, 2011
% Afreen Siddiqi, siddiqi@mit.edu
%%
classdef TotalResidentialWater < Behavior
    properties
        kitchen;    % the total water demand for kitchen use
        faucets;    % the total water demand for faucets use
        shower;     % the total water demand for showers use
        toilets;    % the total water demand for toilets use
        laundry;    % the total water demand for laundry use
    end
    methods
        %% TotalResidentialWater Constructor
        % Instantiates a new TotalResidentialWater object.
        % 
        % obj = TotalResidentialWater()
        %   obj:            the new TotalResidentialWater object
        %   kitchen:    % the total water demand for kitchen use 
        %   facuets:    % the total water demand for kitchen use 
        %   shower:     % the total water demand for kitchen use 
        %   toilets:    % the total water demand for kitchen use 
        %   laundry:    % the total water demand for kitchen use 

        function obj = TotalResidentialWater()
            obj = obj@Behavior('Total Residential Water Demand per Year', ...
                ['Calculates the total residential water demand ' ...
                'in the city by application type.'], ...
                'cubic meters','[0,inf)');
        end
    end
    methods(Access=protected)
        %% EvaluateImpl Function
        % Evaluates the behavior for a specified city. Note: the
        % superclass Evaluate function should be used for evaluation during
        % execution.
        %
        % val = obj.EvaluateImpl(city)
        %   val:    the evaluated value
        %   obj:    the TotalResidentialWater object handle
        function val = EvaluateImpl(obj)
            
            % For each building system node, identify residential node and
            % calculate corresponding water demand per node by application.
            % Following this, sum all application values
            
            city = CityNet.instance().city;
            
            % Search for building system identifier       
            for i = 1:length(city.systems)
                if strcmp(city.systems(i).name,'Building')==1
                    ind = i;
                    break
                end
            end      
            
            % Define Number of Residents per cell function
            numberpplcell = NumberResidentsCell;
            
            % Initialize water values
            TotalWater = 0;
            TotalKitchenDemand = 0;
            TotalFaucetsDemand = 0;
            TotalShowerDemand = 0;
            TotalToiletsDemand = 0;
            TotalLaundryDemand = 0;
            
            % For each building system node
            for j = 1:length(city.systems(ind).nodes)
                % If the node is a residential node
                if strcmp(city.systems(ind).nodes(j).type.name,'Residential')==1
                    % Determine amount of water required in node by application
                    
                    % Total Water per node = Water Demand per person x Node
                    % population
                    numberpplcell.cell = city.systems(ind).nodes(j).cell;
                    totalnodalwater = Evaluate(numberpplcell)*...
                    city.systems(ind).nodes(j).GetNodeTypeAttributeValue('waterPerPerson');
                    
                    TotalWater = TotalWater + totalnodalwater;
                
                    % Determine Individual Water Application Fractions by Node
                    TotalKitchenDemand = TotalKitchenDemand + totalnodalwater*...
                        city.systems(ind).nodes(j).GetNodeTypeAttributeValue('waterKitchenPercent');
                    
                    TotalFaucetsDemand = TotalFaucetsDemand + totalnodalwater*...
                        city.systems(ind).nodes(j).GetNodeTypeAttributeValue('waterFaucetsPercent');
                    
                    TotalShowerDemand = TotalShowerDemand + totalnodalwater*...
                        city.systems(ind).nodes(j).GetNodeTypeAttributeValue('waterShowerPercent');
                    
                    TotalToiletsDemand = TotalToiletsDemand + totalnodalwater*...
                        city.systems(ind).nodes(j).GetNodeTypeAttributeValue('waterToiletsPercent');
                    
                    TotalLaundryDemand = TotalLaundryDemand + totalnodalwater*...
                        city.systems(ind).nodes(j).GetNodeTypeAttributeValue('waterLaundryPercent');
            
                end
            end
            
            
            
            %% Assign Outputs
            % Assign values to each handle in class
            % Multiply by 365 to convert daily demand to annual demand 
            val = TotalWater*365;
            obj.kitchen = TotalKitchenDemand*365;
            obj.faucets = TotalFaucetsDemand*365;
            obj.shower = TotalShowerDemand*365;
            obj.toilets = TotalToiletsDemand*365;
            obj.laundry = TotalLaundryDemand*365;
            
            
        end
    end
end